namespace Blitz_Tag.Models
{
    public enum GTZone
    {
        forest,
        city,
        basement,
        canyon,
        beach,
        mountain,
        skyJungle,
        cave,
        cityWithSkyJungle,
        tutorial,
        rotating,
        none,
        Metropolis,
        cityNoBuildings,
        attic,
        arcade,
        bayou,
        customMaps,
        monkeBlocks,
        mall,
        mines,
        arena,
        hoverboard,
        critters,
        ghostReactor,
        monkeBlocksShared,
        ghostReactorTunnel,
        ranked,
        ghostReactorDrill,
        forestWithCity
    }
}
